-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS Kurssi CASCADE;
DROP TABLE IF EXISTS Aihe CASCADE;
DROP TABLE IF EXISTS Termi CASCADE;
DROP TABLE IF EXISTS Opiskelija CASCADE;
DROP TABLE IF EXISTS Termiaihe CASCADE;
DROP TABLE IF EXISTS Kurssiaihe CASCADE;